-- DVS Planning · Build 10.0
-- Migrazione corretta: modello turni, suggerimenti, conferma/blocco e Remote 1–3.

begin;

-- =========================================================
-- 1. Suggerimenti Produzione
-- =========================================================
create table if not exists public.production_suggestions (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint production_suggestions_name_not_blank
    check (btrim(name) <> '')
);

create unique index if not exists production_suggestions_name_ci_key
  on public.production_suggestions (lower(btrim(name)));

-- =========================================================
-- 2. Suggerimenti Film / Programma
-- =========================================================
create table if not exists public.program_suggestions (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now(),
  constraint program_suggestions_name_not_blank
    check (btrim(name) <> '')
);

create unique index if not exists program_suggestions_name_ci_key
  on public.program_suggestions (lower(btrim(name)));

-- =========================================================
-- 3. Nuovi campi della tabella shifts
-- =========================================================
alter table if exists public.shifts
  add column if not exists program_title text,
  add column if not exists is_client boolean not null default false,
  add column if not exists is_double_station boolean not null default false,
  add column if not exists confirmed boolean not null default false,
  add column if not exists confirmed_at timestamptz,
  add column if not exists confirmed_by uuid,
  add column if not exists notes text,
  add column if not exists updated_at timestamptz not null default now();

-- Compatibilità con le build precedenti:
-- il nuovo campo programma viene inizializzato dal vecchio campo film.
update public.shifts
set program_title = film
where program_title is null;

-- =========================================================
-- 4. Vincoli Stato e Tipo lavorazione
-- =========================================================
alter table if exists public.shifts
  drop constraint if exists shifts_status_check;

alter table if exists public.shifts
  add constraint shifts_status_check
  check (status in ('definitivo', 'provvisorio'));

-- Normalizzazione della vecchia dicitura.
update public.shifts
set work_type = 'SOUND'
where work_type = 'SOUND DESIGN';

alter table if exists public.shifts
  drop constraint if exists shifts_work_type_check;

alter table if exists public.shifts
  add constraint shifts_work_type_check
  check (work_type in (
    'EDIT',
    'ASSISTENTE',
    'GRAFICA',
    'COLOR',
    'SOUND',
    'REDAZIONE'
  ));

-- Un turno CLIENTE non può avere contemporaneamente un dipendente assegnato.
alter table if exists public.shifts
  drop constraint if exists shifts_client_staff_check;

alter table if exists public.shifts
  add constraint shifts_client_staff_check
  check (not (is_client and staff_id is not null));

-- =========================================================
-- 5. Indici
-- =========================================================
create index if not exists shifts_date_room_build10_idx
  on public.shifts (shift_date, room_code, start_time);

create index if not exists shifts_staff_date_build10_idx
  on public.shifts (staff_id, shift_date);

create index if not exists shifts_confirmed_idx
  on public.shifts (confirmed, shift_date);

-- =========================================================
-- 6. Remote 1, Remote 2 e Remote 3
-- =========================================================
-- Se le Remote esistono già, spostiamo temporaneamente il loro sort_order
-- per evitare collisioni durante l'aggiornamento della chiave univoca.
with existing_remote as (
  select code,
         row_number() over (order by code) as rn
  from public.rooms
  where code in ('remoto-1', 'remoto-2', 'remoto-3')
)
update public.rooms r
set sort_order = -1000 - e.rn
from existing_remote e
where r.code = e.code;

with next_order as (
  select coalesce(max(sort_order), 0) as last_order
  from public.rooms
  where code not in ('remoto-1', 'remoto-2', 'remoto-3')
),
remote_rooms (code, display_name, position) as (
  values
    ('remoto-1', 'Remote 1', 1),
    ('remoto-2', 'Remote 2', 2),
    ('remoto-3', 'Remote 3', 3)
)
insert into public.rooms (
  code,
  display_name,
  group_name,
  room_type,
  sort_order,
  active
)
select
  r.code,
  r.display_name,
  'Remote',
  'remoto',
  n.last_order + r.position,
  true
from remote_rooms r
cross join next_order n
on conflict (code) do update
set display_name = excluded.display_name,
    group_name = excluded.group_name,
    room_type = excluded.room_type,
    sort_order = excluded.sort_order,
    active = excluded.active;

commit;
